name: Python API Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  TEST_URL: ${{ secrets.TEST_URL }}
  TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
  TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with Allure
        run: |
          source venv/bin/activate
          export PYTHONPATH="${{ github.workspace }}"
          pytest tests/ --alluredir=results/

      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: results/
